version = 1

test_patterns = ["**/*_test.go", "_fixtures"]

exclude_patterns = ["vendor"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_path = "github.com/go-delve/delve"
  dependencies_vendored = true
