version = 1

test_patterns = ["**/*_test.go"]

exclude_patterns = ["vendor/**", "_fixtures/**", "_scripts/**"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_path = "github.com/go-delve/delve"
  dependencies_vendored = true
